name: Publish to Qiita

on:
  workflow_dispatch:
  push:
    paths: [ "articles/**" ]
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      # 1) トークンがセットされているかチェック
      - name: Check token presence
        env:
          QIITA_TOKEN: ${{ secrets.QIITA_TOKEN }}
        run: |
          if [ -z "$QIITA_TOKEN" ]; then
            echo "ERROR: QIITA_TOKEN is empty"; exit 1; fi
          echo "QIITA_TOKEN is set."

      # 2) トークンが有効かAPIで検証（401なら権限/値ミス）
      - name: Verify token with Qiita API
        env:
          QIITA_TOKEN: ${{ secrets.QIITA_TOKEN }}
        run: |
          code=$(curl -s -o /tmp/me.json -w '%{http_code}' \
