name: Publish to Qiita

on:
  workflow_dispatch:
  push:
    paths: [ "articles/**" ]
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      # 何が見えているか確認
      - name: Debug files
        run: |
          pwd
          ls -la
          find . -maxdepth 3 -type f -print

      # articles/ を作業ディレクトリにして、配下の .md を一括投稿
      - name: Publish all in articles
        working-directory: articles
        env:
          QIITA_TOKEN: ${{ secrets.QIITA_TOKEN }}
        run: npx @qiita/qiita-cli@latest publish .
